version: '3.1'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: asSFas23SAD
      POSTGRES_DB: wallet_service_db
    ports:
      - "5432:5432"